version: '3'

services:
  nodejs:
    container_name: backend
    command: node app.js
    build: ./server
    volumes:
      - .:/usr/app/
    ports:
      - '8000:8000'
  react-frontend:
    container_name: frontend
    command: ["yarn", "start"]
    build: ./client
    volumes:
      - ./client:/app/client
    ports:
      - '3000:3000'